[tool.poetry]
name = "py-aws-core"
version = "0.1.221"
description = "Core package for interfacing with AWS"
authors = ["services <services@rydeas.com>"]
readme = "README.md"
package-mode = true

[tool.poetry.dependencies]
boto3 = "~1.34"
coverage = "~7.5"
python = "~3.12"
python-dotenv = "~1.0"
httpx = "^0.27.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
