# [metadata]
settings_file_name = "settings.toml"

# [directories]
DATA_DIR = "data/"

# [directories.datasets]
DATASET_DIR = "datasets/"
BRONZE_DIR = "bronze/"
SILVER_DIR = "silver/"
GOLD_DIR = "gold/"

# [directories.misc]
LOGS_DIR = 'logs/'
MODELS_DIR = 'models/'
GRAPHS_DIR = 'graphs/' 
REPORTS_DIR = 'reports/'

# [creation.files]
PLAYERS_NAME = "nba_players.csv"
PLAYERS_BASIC_NAME = "nba_players_basic.csv"
PLAYERS_ADVANCED_NAME = "nba_players_advanced.csv"

# [dataset.files]
DATA_FILE_NAME = "nba_player_stats.csv"
DATA_FILE_NAME_JSON = "nba_player_stats.json"
DATA_FILE_5YEAR_NAME = "nba_player_stats_5years.csv"
DATA_FILE_5YEAR_TENSOR_NAME = "nba_player_stats_5years_tensor_ready.csv"
DATA_FILE_5YEAR_OVERLAP = "nba_player_stats_5years_overlap.npz"
DATA_FILE_5YEAR_JSON_NAME = "nba_player_stats_5years.json"

# [models.variables]
FILTER_AMT = 5

[environment]
LOCAL = true  # "local|true", "azure|false"

[cloud]
# Set Azure/Fabric credientials per user
DATALAKE_ACCOUNT_NAME = 'your_datalake_account_name'
DATALAKE_ACCOUNT_KEY = 'your_datalake_account_key'
DATALAKE_ACCOUNT_URI = 'https://{}.dfs.core.windows.net'
DATALAKE_FILESYSTEM_NAME = 'your_datalake_filesystem_name'
DATALAKE_DIRECTORY_PATH = 'your_datalake_directory_path'
SERVER_CONNECTION_STRING = 'your_server_connection_string'
DATALAKE_SQL_CONNECTION_STRING = 'your_datalake_sql_connection_string'

SQL_SERVER_DOMAIN = '.database.windows.net'
SQL_SERVER_NAME = ''
SQL_DATABASE_NAME = ''
SQL_TABLE_NAME = ''
SQL_USERNAME = ''
SQL_PASSWORD = ''

# [cloud.dataset.files]
DATA_FILE_NAME = "nba_player_stats.parquet"
DATA_FILE_NAME_JSON = "nba_player_stats.json"
DATA_FILE_5YEAR_NAME = "nba_player_stats_5years.parquet"
DATA_FILE_5YEAR_TENSOR_NAME = "nba_player_stats_5years_tensor_ready.parquet"
DATA_FILE_5YEAR_OVERLAP = "nba_player_stats_5years_overlap.parquet"
DATA_FILE_5YEAR_JSON_NAME = "nba_player_stats_5years.json"
