[tool.poetry]
name = "hello-baby"
packages = [
    { include = "hello_baby" },
]
version = "2.1.0"
description = ""
authors = ["younthing <fanxingfu3344@gmail.com>"]
readme = "README.md"

[tool.poetry.scripts]
hello-baby = "hello_baby.main:app"

[tool.poetry.dependencies]
python = "^3.11"
sphinx = "^7.4.7"
sphinx-book-theme = "^1.1.3"


[tool.poetry.group.dev.dependencies]
pytest = "^8.2.2"
pytest-cov = "^5.0.0"
black = "^24.4.2"
isort = "^5.13.2"
flake8 = "^7.1.0"
bandit = "^1.7.9"
safety = "^3.2.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

