[tool.poetry]
name = "mpd-tpd"
version = "0.2.1"
description = "Python command-line tool for helping conceptualise how much money is left until payday"
authors = ["J-sephB-lt-n <joseph.jazz.bolton@gmail.com>"]
license = "GPL-3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
mpd-tpd = "mpd_tpd.cli:commandline_mpd_tpd"

[project.urls]
Homepage = "https://github.com/J-sephB-lt-n/mpd-tpd"
