[tool.poetry]
name = "data_transformations_project"
version = "0.1.0"
description = "A library for common data transformations"
authors = ["pratik_thakur <pratikthakur08@yahoo.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.21"

[tool.poetry.dev-dependencies]
pytest = "^6.2"

[tool.poetry.group.dev.dependencies]
black = "^24.4.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"