[build-system]
requires = ["setuptools", "cmake", "pybind11"]
build-backend = "setuptools.build_meta"

[project]
name = "jwm.robotstxt"
version = "1.0.7"
description = "Provides python access to Googles parser for robot.txt files as used by their GoogleBot webscraper."
readme = "README.md"
authors = [{ name = "Joel Morley", email = "jwmorley73@gmail.com" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
keywords = ["robotstxt", "wrapper", "google", "parser"]
requires-python = ">=3.10"
dependencies = []

[project.optional-dependencies]
doc = [
    "sphinx",
    "furo"
]

test = [
    "coverage",
    "pytest"
]

format = [
    "isort",
    "black",
    "clang-format"
]

dev = [
    "jwm.robotstxt[doc, test, format]",
    "cibuildwheel",
    "setuptools",
    "cmake",
    "pybind11"
]

[project.urls]
Homepage = "https://github.com/jwmorley73/jwm.robotstxt"
Documentation = "https://jwmorley73.github.io/jwm.robotstxt/"

[tool.setuptools.data-files]
robotstxt = ["robotstxt/*"]
tests = ["tests/**/*.*"]
docs = ["docs/**/*.*"]

[tool.pytest.ini_options]
minversion = 6.0
console_output_style = "count"
addopts = ["--import-mode=importlib"]
testpaths = ["tests"]

[tool.cibuildwheel]
test-extras = ["test"]
test-command = "python -m coverage run -m pytest {package}/tests"
# Skip 32 bit platforms for now. Will need to find a way of building
# robotstxt on 32 bit platforms.
skip = ["cp310-win32", "cp311-win32", "cp312-win32", "cp313-win32"]