[tool.poetry]
name = "py2ls"
version = "0.1.6.4"
description = "py(thon)2(too)ls"
authors = ["Jianfeng <Jianfeng.Liu0413@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"

appnope = "^0.1.4"
appscript = "^1.2.5"
asttokens = "^2.4.1"
attrs = "^23.2.0"
beautifulsoup4 = "^4.12.3"
certifi = "^2024.6.2"
chardet = "^3.0.4"
charset-normalizer = "^3.3.2"
click = "^8.1.7"
colorcet = "^3.1.0"
coloredlogs = "^15.0.1"
comm = "^0.2.2"
contourpy = "^1.2.1"
cycler = "^0.12.1"
debugpy = "^1.8.1"
decorator = "^5.1.1"
defusedxml = "^0.7.1"
Deprecated = "^1.2.14"
docx = "^0.2.4"
docx2pdf = "^0.1.8"
executing = "^2.0.1"
fake-useragent = "^1.5.1"
flatbuffers = "^24.3.25"
fonttools = "^4.53.0"
fpdf = "^1.7.2"
googletrans = "^4.0.0rc1"
h11 = "^0.9.0"
h2 = "^3.2.0"
hpack = "^3.0.0"
hstspreload = "^2024.6.1"
httpcore = "^0.9.1"
httpx = "^0.13.3"
humanfriendly = "^10.0"
hyperframe = "^5.2.0"
idna = "^2.10"
imageio = "^2.34.1"
img2pdf = "^0.5.1"
ipykernel = "^6.29.4"
ipython = {version = "^8.25.0", python = ">=3.9, <4.0"}
jedi = "^0.19.1"
Jinja2 = "^3.1.4"
joblib = "^1.3.2"
jsonschema = "^4.22.0"
jsonschema-specifications = "^2023.12.1"
jupyter_client = "^8.6.2"
jupyter_core = "^5.7.2"
kiwisolver = "^1.4.5"
langdetect = "^1.0.9"
lazy_loader = "^0.4"
libretranslatepy = "^2.1.1"
llvmlite = "^0.42.0"
lxml = "^4.9.4"
MarkupSafe = "^2.1.5"
matplotlib = "^3.8.4"
matplotlib-inline = "^0.1.7"
mne = "^1.6.0"
mpmath = "^1.3.0"
nest-asyncio = "^1.6.0"
networkx = {version = "^3.3", python = ">=3.10, <4.0" }
nltk = "^3.8.1"
numba = "^0.59.1"
numerizer = "^0.2.3"
numpy = "^1.26.4"
onnxruntime = "^1.18.0"
opencv-contrib-python = "^4.9.0.80"
opencv-python = "^4.9.0.80"
opencv-python-headless = "^4.9.0.80"
outcome = "^1.3.0.post0"
packaging = "^24.1"
pandas = "^2.2.2"
pandas-flavor = "^0.6.0"
parso = "^0.8.4"
patsy = "^0.5.6"
pdf2image = "^1.17.0"
pdf2img = "^0.1.2"
pexpect = "^4.9.0"
pikepdf = "^9.0.0"
pillow = "^10.3.0"
pingouin = "^0.5.4"
platformdirs = "^4.2.2"
pooch = "^1.8.2"
prompt_toolkit = "^3.0.47"
protobuf = "^5.27.1"
psutil = "^5.9.8"
ptyprocess = "^0.7.0"
pure-eval = "^0.2.2"
Pygments = "^2.18.0"
PyMatting = "^1.1.12"
pyparsing = "^3.1.2"
PyPDF2 = "^3.0.1"
PySocks = "^1.7.1"
python-box = "^7.2.0"
python-dateutil = "^2.9.0.post0"
python-docx = "^1.1.0"
python-dotenv = "^1.0.1"
pytz = "^2024.1"
PyYAML = "^6.0.1"
pyzmq = "^26.0.3"
referencing = "^0.35.1"
regex = "^2024.5.15"
rembg = { version  = "^2.0.56", python = ">=3.9, <3.13"}
requests = "^2.32.3"
rfc3986 = "^1.5.0"
rpds-py = "^0.18.1"
SciencePlots = "^2.1.1"
scikit-image = { version = "^0.23.2", python = ">=3.10,<4.0" }
scikit-learn = "^1.3.2"
scipy = "^1.13.1"
seaborn = "^0.13.2"
selenium = "^4.21.0"
six = "^1.16.0"
sniffio = "^1.3.1"
sortedcontainers = "^2.4.0"
soupsieve = "^2.5"
stack-data = "^0.6.3"
statsmodels = "^0.14.1"
stem = "^1.8.2"
sympy = "^1.12.1"
tabulate = "^0.9.0"
threadpoolctl = "^3.5.0"
tifffile = "^2024.5.22"
tornado = "^6.4.1"
tqdm = "^4.66.4"
traitlets = "^5.14.3"
translate = "^3.6.1"
trio = "^0.25.1"
trio-websocket = "^0.11.1"
typing_extensions = "^4.12.2"
tzdata = "^2024.1"
urllib3 = "^2.2.1"
wcwidth = "^0.2.13"
webdriver-manager = "^4.0.1"
wrapt = "^1.16.0"
wsproto = "^1.2.0"
xarray = "^2024.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
