[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "python_selenium_ctrl_package"
version = "0.0.236"
authors = [
  { name="QHMS(App team)", email="qhmsqaexpert@gmail.com" },
]
description = "Base_page for selenium automation"
#keywords = ['python', 'automation', 'appium', 'selenium', 'pytest', 'automation framework']
#dependencies = ['requests', 'reportportal-client', 'pytest', 'selenium', 'python_dotenv', 'Appium_Python_Client', 'pytest-xdist', 'pytest-html', 'pytest-rerunfailures', 'pytest_reportportal', 'pillow', 'tesults', 'loguru', 'imageio', 'questionary', 'clear-screen', 'prompt-toolkit', 'openpyxl', 'pytest-bdd', 'pandas', 'webdriver-manager', 'PyHamcrest']
dependencies = [
    "requests==2.25.1",
    "reportportal-client==5.2.5",
    "pytest==7.4.4",
    "selenium==4.17.2",
    "python_dotenv==0.16.0",
    "Appium_Python_Client==3.1.1",
    "pytest-xdist>=1.31",
    "pytest-html>=3.2.0",
    "pytest-rerunfailures>=9.1.1",
    "pytest_reportportal==5.0.10",
    "pillow>=9.3.0",
    "tesults",
    "loguru==0.6.0",
    "imageio~=2.9.0",
    "questionary>=1.9.0",
    "clear-screen>=0.1.14",
    "prompt-toolkit==2.0.10",
    "openpyxl==3.1.2",
    "pytest-bdd~=6.1.1",
    "pandas~=2.0.0",
    "PyHamcrest",
    "webdriver-manager",
    "python-selenium-ctrl-package"
]
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
