[tool.poetry]
name = "rag-doc-search"
version = "0.1.8"
description = "This package offers a lightweight and straightforward solution for implementing Retrieval-augmented generation (RAG) functionality with large language models (LLMs)."
authors = ["Harshad Kadam <harshad.kadam@sourcefuse.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
boto3 = "^1.34.55"
botocore = "^1.34.55"
langchain = "^0.2.9"
opensearch-py = "^2.4.2"
faiss-cpu = "^1.8.0"
openai = "^1.35.15"
langchain-openai = "^0.1.17"
tiktoken = "^0.7.0"
pgvector = "^0.2.5"
psycopg2-binary = "^2.9.9"
setuptools = "^71.0.3"
django = "4.2.14"
jinja2 = "^3.1.4"
langchain-community = "^0.2.7"
langchain-aws = "^0.1.11"


[tool.isort]
profile = "black"

[tool.poetry.group.dev.dependencies]
black = "^24.4.2"
isort = "^5.13.2"
flake8 = "^7.1.0"
safety = "^3.2.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"