[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name='libMyCarrier'
version='v0.1.1'
readme='README.md'
description=''
license = {file = "LICENSE"}
dependencies= [
    'hvac',
    'pyodbc',
    'azure.identity',

]
authors = [
  { name="MyCarrier-DevOps", email="sre@mycarrier.io" },
]

[project.urls]
Repository = "https://github.com/MyCarrier-DevOps/libMyCarrier.git"
