[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "STVQC_thebiglmaoski"
version = "0.0.1"
authors = [
  { name="Noah Khan", email="noahkhan022@gmail.com" },
  { name="Hanad Elmi", email="slaychomc@gmail.com" }
]
description = "Implementation of the ST-VQC in TorchQuantum"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/jinyang001/ST-VQC/tree/main"
Issues = "https://github.com/jinyang001/ST-VQC/issues"